---
  - name: ':: token :: fetching token from master'
    command: "/bin/cat {{ k8s_token_path }}"
    register: k8s_remote_token

  - name: ':: token :: setting token as fact'
    set_fact:
      k8s_cluster_token: '{{ k8s_remote_token.stdout }}'

  - debug:
      msg: "{{ k8s_cluster_token }}"
